### ISSUE TITLE
Invalid docker-compose file

### ISSUE THREAD

**Issue by apttx** [authcompanion/authcompanion#31]
```shell
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.migrate.depends_on contains an invalid type, it should be an array
```

Checked out repo, ran docker-compose (as readme instructs).

On Ubuntu 20.04.2 LTS with docker-compose 1.26.2 build eefe0d31.

**Comment by pmprosociety** [comment]
Thanks for taking the time to report @apttx - we are reviewing in the next couple days.

**Comment by pmprosociety** [comment]
Hi @apttx hope to give this some love soon - we've been heads down on https://github.com/pmprosociety/authcompanion/pull/32

**Comment by authcompanion** [comment]
👋 @apttx Thanks again for the report -

1) Your docker-compose 1.26.2 is from (2020-07-02) - if you can, upgrading to 1.29.0+ will fix the issue. I'm relying on a new feature of docker-compose to make sure the database is properly setup 👍. 

2) OR replace the 'docker-compose.yml' file with the contents below instead. Give that a shot. In your console hopefully you should see `db-migration | 1/u create_users (92.441ms)`, if not the database might not be ready - in that case we can try other options together. 

```
# docker-compose for development stack of AuthC
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: authc-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mydbsecretpwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3000:8080

  migrate:
    build: .
    image: authcompanion
    container_name: db-migration
    env_file:
      - .env
    depends_on:
      - db
    command: ./migrate.linux-amd64 -source file://db/migrations -database "postgres://$DB_USER:$DB_PASSWORD@$DB_HOSTNAME:$DB_PORT/$DATABASE?sslmode=disable" up

  api:
    build: .
    container_name: authc-api
    env_file:
      - .env
    image: authcompanion
    restart: always
    depends_on:
      - migrate
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:3002:3002

volumes:
     dbdata:
```

**Comment by apttx** [comment]
Thanks for looking into it. Figured that would be the issue but thought `version` was supposed to prevent that. Weird.
