### ISSUE TITLE
authc-api crash

### ISSUE THREAD

**Issue by elycheikhsmail** [authcompanion/authcompanion#37]
I follow the instruction in read me  when I run 
docker-compose up
I got this error:
authc-api  | error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
authc-api  |   const readKey = await Deno.readTextFile(path);
authc-api  |                   ^
authc-api  |     at deno:core/01_core.js:106:46
authc-api  |     at unwrapOpResult (deno:core/01_core.js:126:13)
authc-api  |     at async open (deno:runtime/js/40_files.js:51:17)
authc-api  |     at async Object.readTextFile (deno:runtime/js/40_read_file.js:40:18)
authc-api  |     at async importKey (file:///app/helpers/jwtutils.ts:19:19)
authc-api  |     at async file:///app/helpers/jwtutils.ts:37:19
authc-api  | error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
authc-api  |   const readKey = await Deno.readTextFile(path);
authc-api 
.....

**Comment by authcompanion** [comment]
Hi @elycheikhsmail so sorry about this! I will have a fix in place in a couple hours.

**Comment by elycheikhsmail** [comment]
thank you, you do good job, bug is some thing we inspected in any software

**Comment by authcompanion** [comment]
Hello @elycheikhsmail in the authcompanion directory - can you run the command:

`deno run -A --unstable generateKey.ts`

Then try docker-compose up for a second time and let me know the results.

**Comment by authcompanion** [comment]
I also pushed a new docker-compose version - if you pull the latest changes and run `docker-compose up --build` - let me know if working for you.
